/**
 * Sidebar konfigurace — AUTOGENERATED
 * ====================================
 * Docusaurus automaticky scanuje docs/ složku.
 * Řazení a labely se řídí:
 *   - _category_.json v každé složce (label, position)
 *   - frontmatter v MD souborech (sidebar_label, sidebar_position)
 *
 * Přidání/odebrání souborů v docs/ se projeví automaticky.
 * Není potřeba ručně udržovat tento soubor.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  mainSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
